#!/bin/sh
# This is the script I use to keep the Porting/ stuff up-to-date
# with the latest Configure.
#  Andy Dougherty   	July 14, 1998

rm -f config.sh Policy.sh
cat >Policy.sh <<'EOP'
libswanted="cl pthread $libswanted"
EOP

sh ./Configure -Dprefix=/opt/perl \
	-Dcf_by='merijn' \
	-Dcf_email='yourname@yourhost.yourplace.com' \
	-Dperladmin='yourname@yourhost.yourplace.com' \
	-Dmydomain='.yourplace.com' \
	-Dmyhostname='yourhost' \
	-Duse64bitint \
	-Dusedevel \
	-dE
test $? = 0 || exit 1
chmod u+w Porting Porting/Glossary Porting/config*
cp config.sh Porting/config.sh
sh config_h.SH
cat <<'EOCP' > Porting/config_H
/* This file (config_H) is a sample config.h file.  If you are unable
   to successfully run Configure, copy this file to config.h and
   edit it to suit your system.
*/
EOCP
cat config.h >> Porting/config_H
rm config.sh config.h
if newer Configure Porting/Glossary; then
    pwd=`pwd`
    U/mkgloss.pl >Porting/Glossary
#    cd Porting
#    rm -f Glossary.rej
#    # The standard 'dist' units contain some strings that upset
#    # pod2man.  This patch silences pod2man's warnings.
#    patch < $pwd/U/Glossary.patch
#    if test -f Glossary.rej; then
#	echo 'Check possible failed patch to Porting/Glossary!'
#	exit 2
#	fi
#    cd $pwd
    fi
# Remove detritus.
#if test -f makeaperl -a -f pod/Makefile; then
#    rm -f cflags config.h cppstdin makeaperl makedepend makedir Makefile myconfig pod/Makefile Policy.sh writemain x2p/cflags x2p/Makefile Obsolete Wanted
#    fi
